### PR TITLE
Solving issues with the installer

### LINKED ISSUE #1644: Bash script to install nightly does not work
**Describe the bug**
The [getting started guide](https://arturo-lang.io/documentation/getting-started/) suggest using the following bash script to install the latest nightly:

```shell
curl -sSL https://get.arturo-lang.io/latest | sh
```

**To Reproduce**
1. Run `curl -sSL https://get.arturo-lang.io/latest | sh`
2. See error

```
erik@schierheim:~/exercism$ curl -sSL https://get.arturo-lang.io/latest | sh
======================================

               _
              | |
     __ _ _ __| |_ _   _ _ __ ___
    / _` | '__| __| | | | '__/ _ \
   | (_| | |  | |_| |_| | | | (_) |
    \__,_|_|   \__|\__,_|_|  \___/


     Arturo Programming Language
      (c)2023 Yanis Zafirópulos

======================================
 ► Installer
======================================

 ● Checking environment...
   os: x86_64-linux
   shell: bash

 ● Checking prerequisites...
   2 packages can be upgraded. Run 'apt list --upgradable' to see them.

 ● Downloading...curl: no URL specified!
curl: try 'curl --help' or 'curl --manual' for more information
tar (child): /tmp/tmp.COQGG5lfVc/arturo.tar.gz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now

 ● Installing...cp: cannot stat '/tmp/tmp.COQGG5lfVc/arturo': No such file or directory

 ● Cleaning up...

 ● Done!

 :---------------------------------------------------------
 : Arturo has been successfully installed!
 :
 : To be able to run it,
 : first make sure its in your $PATH:
 :
 :    export PATH=/home/erik/.arturo/bin:$PATH
 :
 : and add it to your ~/.bashrc or ~/.profile,
 : so that it's set automatically every time.
 :
 : Rock on! :)
 :---------------------------------------------------------
```

**Expected behavior**
I would have expected the nightly version to be installed.
As the file could not be downloaded, I would also expect this to be acknowledged by the script and not print the "Arturo has been successfully installed!" message :)

**Desktop (please complete the following information):**
 - OS: Windows WSL on Ubuntu
 - Version Windows 11, Ubuntu 23.04

### PR DESCRIPTION
**Pull request by RickBarretto**
* Fixes https://github.com/arturo-lang/arturo/issues/1644

This PR is not fully complete since this won't work on Windows. 
Not because of the script itself, but because of the way we organized the Windows' folder is different.

While the Linux version has the files inside it, the Windows version has another inner folder wrapping our files. Look:

image.

### CODE REVIEW

**Comment by RickBarretto** [comment]
@drkameleon, can you try this later?

**Comment by RickBarretto** [comment]
Also, thanks to @ErikSchierboom for noticing that!
I think the issue when installing was a typo with the Temporary folder's variable.

**Comment by ErikSchierboom** [comment]
I've tested this on my WSL machine and both stable and nightly install correctly. 

My only suggestion would be to somehow make it clear which version is installed. The output looked the same for the nightly and stable versions.

**Review by drkameleon — APPROVED** [review]

**Comment by drkameleon** [comment]
Ready to merge! 🚀

**Pull request merged**
